#!/usr/bin/env python
# coding: utf-8

# In[1]:


str1="hello"
print(str1)
# In[7]:


"hello"[1]


# In[8]:


str1[-1:]


# In[4]:


str[:-1]


# In[5]:


str1[:-1]


# In[22]:


str1="hello"
count=0
print(len(str1))
count= len(str1)
print(count)


# In[21]:


str1="hello"
count=0
for i in str1:
    count=count+1
    print(count)


# In[14]:


str1="hello"
print(str1[0:2]+str1[-2:])

str1="my mom makes cake"
chr1=str1[0]
str2=str1.replace(chr1,'$')
print(chr1+str2[1: ])
# In[23]:


str1="my mom makes cake"
chr1=str1[0]
str2=str1.replace(chr1,'$')
print(chr1+str2[1: ])


# In[26]:


str1="hello"
str2="world"
str3=str1+" "+ str2
print(str3)
print(str2[-2: ]+str1[2: ]+" "+str2[0:3]+str1[0:2])
